services:
  backend:
    build:
      context: ./backend/backend/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    networks:
      - app-network

#frontend:
    #build:
      #context: ./frontend
      #dockerfile: Dockerfile
    #ports:
      #- "3000:3000"
    #networks:
      #- app-network

networks:
  app-network:
    driver: bridge

